FROM python:3.8-alpine
WORKDIR /data
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
COPY . .
RUN ./manage.py migrate
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]